- name: Turning off the swap and removing from fstab
  shell: "swapoff -a"  # && sed -i.bak -r 's/(.+ swap .+)/#\1/' /etc/fstab

- name: Add the overlay module
  modprobe:
    name: '{{ item }}'
    state: present
  loop: '{{ modules }}'   

- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive

- name: Insert templates files
  copy:
    src: '{{ item.value.src }}'
    dest: '{{ item.value.dest }}'
    mode: 644
    force: true
  with_dict: '{{ k8s_templates }}'

- name: Add docker-ce repository
  yum_repository:
    name: docker-ce
    description: YUM Docker Repo
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    # gpgcheck: no

- name: Installing kubernetes base packages
  yum:
    name: '{{ cri_dep }}'
    state: present
    exclude: kubernetes

- name: Installing kubernetes base packages
  yum:
    name: '*'
    state: latest

- name: Installing kubernetes base packages
  yum:
    name: '{{ kube_base }}'
    state: present
    exclude: kubernetes
    #disable_gpg_check: yes

- name: Create the containerd directory
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Generating the default containerd config
  shell: 'containerd config default > /etc/containerd/config.toml'

- name: Replace after the expression till the end of the file (requires Ansible >= 2.4)
  replace:
    path: /etc/containerd/config.toml
    regexp: '^(.*systemd_cgroup).+$'
    replace: '\1 = true'

- name: Loading modes
  shell: 'sysctl --system'

- name: Reload Daemon
  systemd:
    daemon_reload: yes

- name: Start and Enable services
  systemd:
    name: '{{ item }}'
    state: restarted
    enabled: yes
  loop: '{{ kube_base_services }}'

