---
# defaults file for kubecluster
modules:
  - overlay
  - br_netfilter
config_folders:
  - /etc/containerd/
  - /etc/cni/net.d
  - /opt/cni/bin
  - /var/lib/kubelet
  - /var/lib/kube-proxy
  - /var/lib/kubernetes
  - /var/run/kubernetes
  - /tmp/cni
  - /tmp/containerd
  - /tmp/crictl
containerd_dep:
  - socat
  - conntrack
  - ipset
  - wget
containerd_binaries:
  - runc:
      download: https://storage.googleapis.com/kubernetes-the-hard-way/runsc
      dest: /usr/bin/runsc
  - runc_amd64:
      download: https://github.com/opencontainers/runc/releases/download/v1.0.0-rc5/runc.amd64
      dest: /usr/bin/runc
containerd_tar_files:
  - containerd:
      download: https://github.com/containerd/containerd/releases/download/v1.1.0/containerd-1.1.0.linux-amd64.tar.gz
      tar: /tmp/containerd-amd64.tar.gz
      untar: /tmp/containerd/
      subfolders: bin/
      dest: /
  - cni:
      download: https://github.com/containernetworking/plugins/releases/download/v0.6.0/cni-plugins-amd64-v0.6.0.tgz
      tar: /tmp/cni-plugins-amd64.tar.gz
      untar: /tmp/cni/
      subfolders: ""
      dest: /opt/cni/bin/
  - crictl:
      download: https://github.com/kubernetes-incubator/cri-tools/releases/download/v1.0.0-beta.0/crictl-v1.0.0-beta.0-linux-amd64.tar.gz
      tar: /tmp/crictl.tar.gz
      untar: /tmp/crictl/
      subfolders: ""
      dest: /usr/local/bin/
containerd_tpl:
  - config:
      src: config.toml.j2
      dest: /etc/containerd/config.toml
  - servicej2:
      src: containerd.service.j2
      dest: /etc/systemd/system/containerd.service
  - bridge:
      src: 10-bridge.conf.j2
      dest: /etc/cni/net.d/10-bridge.conf
  - loopback:
      src: 99-loopback.conf.j2
      dest: /etc/cni/net.d/99-loopback.conf
pod_cidr: 10.22.0.0
k8s_bin_dep:
  - kubctl:
      download: https://storage.googleapis.com/kubernetes-release/release/v1.10.2/bin/linux/amd64/kubectl
      dest: /usr/local/bin/kubectl
  - kube-proxy:
      download: https://storage.googleapis.com/kubernetes-release/release/v1.10.2/bin/linux/amd64/kube-proxy
      dest: /usr/local/bin/kube-proxy
  - kubelet:
      download: https://storage.googleapis.com/kubernetes-release/release/v1.10.2/bin/linux/amd64/kubelet
      dest: /usr/local/bin/kubelet
k8s_templates:
  - 99-kubernetes-cri:
      src: 99-kubernetes-cri.conf
      dest: /etc/sysctl.d/99-kubernetes-cri.conf
#  - kubernetes-repo:
#      src: kubernetes.repo
#      dest: /etc/yum.repos.d/kubernetes.repo
  - k8sconf:
      src: k8s.conf
      dest: /etc/sysctl.d/k8s.conf
  - kubelet:
      src: kubelet
      dest: /etc/default/kubelet
  - kubelet:
      src: sysctl.conf
      dest: /etc/sysctl.conf
kube_base:
  - kubelet
  - kubeadm
  - kubectl
crio_repo_version: paas7-crio-311-candidate
kube_base_services:
  - containerd.io
  - kubelet
